# Generated by Django 5.0.14 on 2026-09-24 20:33

import common.encryption
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaners', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_summary', models.CharField(help_text="e.g. '14 Okpanam Road, Asaba'", max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cleaners_needed', models.PositiveSmallIntegerField(default=1)),
                ('gender_preference', models.CharField(choices=[('any', 'No preference'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('requested_date', models.DateField()),
                ('requires_access_code', models.BooleanField(default=False)),
                ('access_code_location', models.CharField(blank=True, help_text="Where the code applies, e.g. 'estate gate', 'house gate'.", max_length=100)),
                ('access_code', common.encryption.EncryptedTextField(blank=True, help_text='Encrypted at rest; only decrypted for authorized reads.')),
                ('intake_channel', models.CharField(choices=[('app', 'App'), ('phone', 'Phone-in')], default='app', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('shortlisted', 'Shortlisted'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('timeframe_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('packet_sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='customers.customer')),
                ('taken_by_admin', models.ForeignKey(blank=True, help_text='Admin who logged a phone-in request, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requested_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('timed_out', 'Timed out'), ('withdrawn', 'Withdrawn')], default='recommended', max_length=15)),
                ('rank_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('rank_breakdown', models.JSONField(blank=True, default=dict)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='cleaners.cleaner')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jobs.job')),
            ],
            options={
                'ordering': ['-rank_score'],
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=15)),
                ('to_status', models.CharField(max_length=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.job')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'requested_date'], name='jobs_job_status_64448e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobassignment',
            unique_together={('job', 'cleaner')},
        ),
    ]
